name: Prepare a Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version to prepare (optional)
        required: false
      force:
        description: Force release preparation even when there are release-blockers (optional)
        required: false
  schedule:
    # This is when we release the self-hosted repo
    - cron: "0 18 15 * *"
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    name: "Prepare a new release"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_RELEASE_PAT }}
          fetch-depth: 0
      - name: Prepare release
        uses: getsentry/action-prepare-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        with:
          version: ${{ github.event.inputs.version }}
          force: ${{ github.event.inputs.force }}
          calver: true
